#include "../input.h"

// only supports "press" events so far
const kb_event_t kb_event_map[0x80] = {
    [0x01] = { KEY_PRESSED, INPUT_KEY_ESCAPE },
    [0x02] = { KEY_PRESSED, INPUT_KEY_1 },
    [0x03] = { KEY_PRESSED, INPUT_KEY_2 },
    [0x04] = { KEY_PRESSED, INPUT_KEY_3 },
    [0x05] = { KEY_PRESSED, INPUT_KEY_4 },
    [0x06] = { KEY_PRESSED, INPUT_KEY_5 },
    [0x07] = { KEY_PRESSED, INPUT_KEY_6 },
    [0x08] = { KEY_PRESSED, INPUT_KEY_7 },
    [0x09] = { KEY_PRESSED, INPUT_KEY_8 },
    [0x0A] = { KEY_PRESSED, INPUT_KEY_9 },
    [0x0B] = { KEY_PRESSED, INPUT_KEY_0 },
    [0x0C] = { KEY_PRESSED, INPUT_KEY_DASH },
    [0x0D] = { KEY_PRESSED, INPUT_KEY_EQUAL },
    [0x0E] = { KEY_PRESSED, INPUT_KEY_BACKSPACE },
    [0x0F] = { KEY_PRESSED, INPUT_KEY_TAB },
    [0x10] = { KEY_PRESSED, INPUT_KEY_Q },
    [0x11] = { KEY_PRESSED, INPUT_KEY_W },
    [0x12] = { KEY_PRESSED, INPUT_KEY_E },
    [0x13] = { KEY_PRESSED, INPUT_KEY_R },
    [0x14] = { KEY_PRESSED, INPUT_KEY_T },
    [0x15] = { KEY_PRESSED, INPUT_KEY_Y },
    [0x16] = { KEY_PRESSED, INPUT_KEY_U },
    [0x17] = { KEY_PRESSED, INPUT_KEY_I },
    [0x18] = { KEY_PRESSED, INPUT_KEY_O },
    [0x19] = { KEY_PRESSED, INPUT_KEY_P },
    [0x1A] = { KEY_PRESSED, INPUT_KEY_LEFT_BRACKET },
    [0x1B] = { KEY_PRESSED, INPUT_KEY_RIGHT_BRACKET },
    [0x1C] = { KEY_PRESSED, INPUT_KEY_ENTER},
    [0x1D] = { KEY_PRESSED, INPUT_KEY_LEFT_CONTROL },
    [0x1E] = { KEY_PRESSED, INPUT_KEY_A },
    [0x1F] = { KEY_PRESSED, INPUT_KEY_S },
    [0x20] = { KEY_PRESSED, INPUT_KEY_D },
    [0x21] = { KEY_PRESSED, INPUT_KEY_F },
    [0x22] = { KEY_PRESSED, INPUT_KEY_G },
    // to be continued
};